version: '3.8'

services:
  fastapi:
    build: .
    container_name: darwix-ai-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./data/sales_analytics.db
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - ./data:/app/data
    restart: unless-stopped