version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sales_analytics
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d sales_analytics"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/sales_analytics
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    command: >
      sh -c "
        alembic upgrade head &&
        python -c 'import asyncio; from app.ingestion import DataIngestionPipeline; asyncio.run(DataIngestionPipeline().ingest_data())' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

volumes:
  postgres_data: